config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to  => 'customers#index'
  get '/customers/new', :to => 'customers#new', as: 'new'
  get '/companies/new', :to => 'companies#new'
  get '/companies/index', :to => 'companies#index', as: 'index'
  get '/courier/index', :to => 'courier#index', as: 'courier'
  get '/courier/new', :to => 'courier#new', as: 'data'
  get '/distributors/index', :to => 'distributors#index', as: 'agen'
  get '/distributors/new', :to => 'distributors#new', as: 'stok'
  get '/branches/index', :to => 'branches#index', as: 'citie'
  get '/branches/new', :to => 'branches#new', as: 'branc'

  get '/email', :to => 'customers#email'
 #company a
   post 'customer', to: 'customers#create', as: 'customers'
  post 'companie', to: 'companies#create', as: 'companies'
  post 'courier', to: 'courier#create', as: 'couriers'
  post 'distributor', to: 'distributors#create', as: 'distributors'
  post 'branches', to: 'branches#create', as: 'branches'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branche.rb
class Branche < ApplicationRecord
	# def self.create(params)
		# @branche = Branche.new
		# @branche.city_id = params[:branche][:city_id]
		# @branche.company_id = params[:branche][:company_id]
		# @branche.name = params[:branche][:name]
		# @branche.address = params[:branche][:address]
		# @branche.person_in_charge = params[:branche][:person_in_charge]
		# @branche.phone_number = params[:branche][:phone_number]
		# @branche.email = params[:branche][:email]
		# return @branche
		
	
end

app/models/company.rb
class Company < ApplicationRecord
		has_many :employes
	def self.create(params)
			@company = Company.new
			@company.name = params[:company][:name]
			@company.address = params[:company][:address]
			@company.phone_number = params[:company][:phone_number]
		return @company
	end	

end

app/models/courier.rb
class Courier < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
	def self.create(params)
			@customer = Customer.new
			@customer.name = params[:customer][:name]
			@customer.address = params[:customer][:address]
			@customer.phone_number = params[:customer][:phone_number]
		return @customer model	
	end
end

app/models/distributor.rb
class Distributor < ApplicationRecord
	
end

app/models/employe.rb
class Employe < ApplicationRecord
	belongs_to :company
		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
	def index
		@branche = Branche.all
	end

    def new
    	@branche = Branche.new
    	
    end

    
   def create
   		# @branche = Branche.create(params)
   		# if @branche.save
   		# 	flash[:success]
   		# else
   		# 	redirect_to root_path
   	end


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController


	def new
		@companie = Company.new a

	end



	def create

		@companie = Company.create(params) c

			# :name => params[:company][:name],
			# :address => params[:company][:address],
			# :phone_number => params[:company][:phone_number])
            if @companie.save
            	flash[:success]
            	else
            end	
		redirect_to root_path
		
	end

	def index
		@companie = Company.where("name like '%#{params[:kata_kunci]}%' or address like '%#{params[:kata_kunci]}%' or phone_number like '%#{params[:kata_kunci]}%'")
	end
end

app/controllers/courier_controller.rb
class CourierController < ApplicationController
	def index
		@courier = Courier.all
		
	end


	def create

	end



	def new
		
	end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def email
		@customer = Customer.find(params[:id])
		CustomerMailer.email(@customer.phone_number,@customer.address).deliver aris
   end

	# def update
	# 	@customer = Customer.find(params[:id]
 #      respond_to do |format|
 #        if @customer.update customer_params
 #           ...
 #      	end
		
	# end



	def new
		@customer = Customer.new
	end



	def create
       @customer = Customer.create(params)c
       	# :name => params[:customer][:name],
       	# :address => params[:customer][:address],
       	# :phone_number => params[:customer][:phone_number])
       	if @customer.save

       		flash[:success]b
       		# CustomerMailer.kirim_email(@customer.address, "selamat bergabung bos").deliver

       		redirect_to root_path
	    else 
	        # render [:action] => 'new'
       	end
	end


	def index 
		@customer = Customer.where("name like '%#{params[:kata_kunci]}%' or address like '%#{params[:kata_kunci]}%' or phone_number like '%#{params[:kata_kunci]}%'")
	end
end

app/controllers/distributors_controller.rb
class DistributorsController < ApplicationController
	def index
		
	end

	def new
		
	end




	def create
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/courier_helper.rb
module CourierHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/distributors_helper.rb
module DistributorsHelper
end

app/views/branches/index.html.erb
<!DOCTYPE html>
<html>
<head>
<body>
	<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>
     <form>

     <input type="text" name="kata_kunci">
     <input type="submit" name="" value="cari data">	
     </form>
<h2>Branches</h2>

<table>
  <tr>
    <center> <th>city Id</th>
    <th>Company_id</th>
    <th>Address</th>
    <th>Person in charge</th>
    <th>Phone Number</th>
    <th>Email</th>
    <th></th>
  </tr>
   <% @branche.each do |data| %>
  <tr>
    <td><%= data.city_id %></td>
    <td><%= data.company_id %></td>
    <td><%= data.address %></td>
    <td><%= data.person_in_charge%></td>
    <td><%= data.phone_number %></td>
    <td><%= data.email %></td>

  </tr>
 <% end %>
   
</table>
<%= link_to 'new', branc_path %>
<%= link_to 'table', index_path %>
</body>
</html>

app/views/branches/new.html.erb
hgvgubhugbyuguyguyf

app/views/companies/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<style>
		table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>
     <form>
     	<input type="text" name="kata_kunci">
     	<input type="submit" name="cari data">
     </form>

     <center><h2>Companies</h2>

<table style="width:100%">
  <tr>
    <h2><th>Name</th></h2>
    <h2><th>Address</th></h2>
    <h2><th>Phone number</th></h2>
  </tr>
  <% @companie.each do |data| %>
  <tr>
    <th><%= data.name %></th>
    <th><%= data.address %></th>
    <th><%= data.phone_number %></th>
  </tr></center>
  <% end %>
</table>
		<%= link_to 'new', new_path %>
		<%= link_to 'table', companies_new_path %>
    redirect to ams_racing_team_racing
</body>
</html>

app/views/companies/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<center><h1>input data company</h1>
		<%= form_for @companie do |data_form| %>
			<%= data_form.text_field :name %>
			<%= data_form.text_field :address %>
			<%= data_form.text_field :phone_number %>
			<%= data_form.submit 'daftar' %>
		<% end %>
		<%= link_to "text", index_path %>
		<%= link_to "text", companies_new_path %></center>
</body>
</html>

app/views/courier/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<input type="text" name="kata_kunci">
	<input type="submit" name="daftar">

		<h2>courier</h2>
    <tr>
		<th>Name</th>
		<th>Address</th>
		<th>Phone number</th>
		<th>Email</th>
		<th>No sim</th>
	  </tr>	
	<% @courier.each do |data| %>

	<tr>
		<th><%= data.name %></th>
		<th><%= data.address %></th>
		<th><%= data.phone_number %></th>
		<th><%= data.no_sim %></th>
	</tr>
	<% end %>
  

</body>
</html>

app/views/customers/email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Welcome to example.com, <%= @customer.name %></h1>
    <p>
      You have successfully signed up to example.com,
      your username is: <%= @customer.phone_number %>.<br>
    </p>
    <p>
      To login to the site, just follow this link: <%= @url %>.
    </p>
    <p>Thanks for joining and have a great day!</p>
  </body>
</html>

app/views/customers/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>
     <form>

     <input type="text" name="kata_kunci">
     <input type="submit" name="" value="cari data">	
     </form>
<h2>data pelanggan</h2>

<table>
  <tr>
    <center> <th>Id</th>
    <th>nama</th>
    <th>alamat</th>
    <th>no telepon</th>
    <th>Email</th>
    <th>Update</th>
    <th>Delete</th>
    <th></th>
  </tr>
   <% @customer.each do |data| %>
  <tr>
    <td><%= data.id %></td>
    <td><%= data.name %></td>
    <td><%= data.address %></td>
    <td><%= data.phone_number %></td>
    <td><%= link_to 'kirim email', {:controller =>  "customers",:action => "email", :id => data.id} %></td>
   <td><%= link_to 'update' %></td>
    <td><%= link_to 'delete' %></td></center>

  </tr>
 <% end %>
   
</table>
<%= link_to 'new', new_path %>
<%= link_to 'table', index_path %>
<%= link_to 'courier', courier_path %>

</body>
</html>

app/views/customers/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<center><h1>input data customer</h1>
       <%= form_for @customer do |data_form| %>
       	    <%= data_form.text_field :name %>
       	    <%= data_form.text_field :address %>
       	    <%= data_form.text_field :phone_number %>
       	    <%= data_form.submit 'daftar'%>
                  penambahan data
       <% end %>
       <%= link_to "text", root_path %>
       <%= link_to "text", new_path %></center>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rimbaraya</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>